Repository JelteF/derive_more, pull requests merged in 2023-12, with the labels that each got.

#322 Delegation for `fmt` traits (#321)
  CHANGELOG.md
  impl/doc/debug.md
  impl/doc/display.md
  impl/src/fmt/debug.rs
  impl/src/fmt/display.rs
  impl/src/fmt/mod.rs
  impl/src/fmt/parsing.rs
  impl/src/parsing.rs
  impl/src/utils.rs
  tests/debug.rs
  tests/display.rs
Labels: enhancement

#325 Update links to derive docs in README to point to beta
  README.md
Labels: docs

#326 Fix private docs
  .github/workflows/ci.yml
  impl/src/as/mod.rs
  impl/src/fmt/display.rs
  impl/src/fmt/mod.rs
  impl/src/from.rs
  impl/src/into.rs
  impl/src/parsing.rs
  impl/src/try_from.rs
  impl/src/utils.rs
Labels: docs, github_actions

#327 Better hygiene for `core` crate naming (#180)
  CHANGELOG.md
  impl/src/add_assign_like.rs
  impl/src/add_like.rs
  impl/src/as/mod.rs
  impl/src/error.rs
  impl/src/fmt/debug.rs
  impl/src/fmt/display.rs
  impl/src/from.rs
  impl/src/from_str.rs
  impl/src/into.rs
  impl/src/not_like.rs
  impl/src/sum_like.rs
  impl/src/try_from.rs
  impl/src/try_into.rs
  impl/src/utils.rs
  src/lib.rs
Labels: enhancement
